services:
  user-app:
    build: ./apps/user-app
    container_name: taaza-user-app
    ports:
      - "3000:80"
    depends_on:
      - auth-service
    networks:
      - taaza-network

  admin-app:
    build: ./apps/admin-app
    container_name: taaza-admin-app
    ports:
      - "3001:80"
    depends_on:
      - auth-service
    networks:
      - taaza-network

  auth-service:
    build: ./services/auth-service
    container_name: taaza-auth-service
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://taaza_user:taaza_pass@postgres:5432/taaza_db?sslmode=disable
      - SMTP_EMAIL=amarnathmalasani2@gmail.com
      - SMTP_PASSWORD=eiustppewepd cuxz
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - taaza-network

  postgres:
    image: postgres:15-alpine
    container_name: taaza-postgres
    environment:
      - POSTGRES_USER=taaza_user
      - POSTGRES_PASSWORD=taaza_pass
      - POSTGRES_DB=taaza_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - taaza-network

volumes:
  postgres-data:


networks:
  taaza-network:
    driver: bridge
